import Mascara from "../image/Mascara.webp"
export const categories = [
    {
      sub: '💕New launches💕',
      posts: [
        {
          id: 1,
          imgsrc:Mascara,
          title: 'Serum-infused volume boost Mascara....',
          Highlight: 'instant volume | waterproof | 24 Hours stay',
          Price: 'MRP ₹499.00',
          path: '/*',
        },
        {
            id: 2,
            imgsrc:Mascara,
            title: 'Serum-infused volume boost Mascara....',
            Highlight: 'instant volume | waterproof | 24 Hours stay',
            Price: 'MRP ₹499.00',
            path: '/*',
          },
          {
            id: 3,
            imgsrc:Mascara,
            title: 'Serum-infused volume boost Mascara....',
            Highlight: 'instant volume | waterproof | 24 Hours stay',
            Price: 'MRP ₹499.00',
            path: '/*',
          },
          {
            id: 4,
            imgsrc:Mascara,
            title: 'Serum-infused volume boost Mascara....',
            Highlight: 'instant volume | waterproof | 24 Hours stay',
            Price: 'MRP ₹499.00',
            path: '/*',
          },
          {
            id: 5,
            imgsrc:Mascara,
            title: 'Serum-infused volume boost Mascara....',
            Highlight: 'instant volume | waterproof | 24 Hours stay',
            Price: 'MRP ₹499.00',
            path: '/*',
          },
          {
            id: 6,
            imgsrc:Mascara,
            title: 'Serum-infused volume boost Mascara....',
            Highlight: 'instant volume | waterproof | 24 Hours stay',
            Price: 'MRP ₹499.00',
            path: '/*',
          },
      ],
    },
    {
      sub: 'Best sellers',
      posts: [
        {
            id: 1,
            imgsrc:Mascara,
            title: 'Serum-infused volume boost Mascara....',
            Highlight: 'instant volume | waterproof | 24 Hours stay',
            Price: 'MRP ₹499.00',
            path: '/*',
          },
          {
              id: 2,
              imgsrc:Mascara,
              title: 'Serum-infused volume boost Mascara....',
              Highlight: 'instant volume | waterproof | 24 Hours stay',
              Price: 'MRP ₹499.00',
              path: '/*',
            },
            {
              id: 3,
              imgsrc:Mascara,
              title: 'Serum-infused volume boost Mascara....',
              Highlight: 'instant volume | waterproof | 24 Hours stay',
              Price: 'MRP ₹499.00',
              path: '/*',
            },
            {
              id: 4,
              imgsrc:Mascara,
              title: 'Serum-infused volume boost Mascara....',
              Highlight: 'instant volume | waterproof | 24 Hours stay',
              Price: 'MRP ₹499.00',
              path: '/*',
            },
            {
              id: 5,
              imgsrc:Mascara,
              title: 'Serum-infused volume boost Mascara....',
              Highlight: 'instant volume | waterproof | 24 Hours stay',
              Price: 'MRP ₹499.00',
              path: '/*',
            },
            {
              id: 6,
              imgsrc:Mascara,
              title: 'Serum-infused volume boost Mascara....',
              Highlight: 'instant volume | waterproof | 24 Hours stay',
              Price: 'MRP ₹499.00',
              path: '/*',
            },
      ],
    },
    {
      sub: 'Gifting',
      posts: [
        {
            id: 1,
            imgsrc:Mascara,
            title: 'Serum-infused volume boost Mascara....',
            Highlight: 'instant volume | waterproof | 24 Hours stay',
            Price: 'MRP ₹499.00',
            path: '/*',
          },
          {
              id: 2,
              imgsrc:Mascara,
              title: 'Serum-infused volume boost Mascara....',
              Highlight: 'instant volume | waterproof | 24 Hours stay',
              Price: 'MRP ₹499.00',
              path: '/*',
            },
            {
              id: 3,
              imgsrc:Mascara,
              title: 'Serum-infused volume boost Mascara....',
              Highlight: 'instant volume | waterproof | 24 Hours stay',
              Price: 'MRP ₹499.00',
              path: '/*',
            },
            {
              id: 4,
              imgsrc:Mascara,
              title: 'Serum-infused volume boost Mascara....',
              Highlight: 'instant volume | waterproof | 24 Hours stay',
              Price: 'MRP ₹499.00',
              path: '/*',
            },
            {
              id: 5,
              imgsrc:Mascara,
              title: 'Serum-infused volume boost Mascara....',
              Highlight: 'instant volume | waterproof | 24 Hours stay',
              Price: 'MRP ₹499.00',
              path: '/*',
            },
            {
              id: 6,
              imgsrc:Mascara,
              title: 'Serum-infused volume boost Mascara....',
              Highlight: 'instant volume | waterproof | 24 Hours stay',
              Price: 'MRP ₹499.00',
              path: '/*',
            },
      ],
    },
  ]